---
- name: Add k8s repo
  yum_repository:
    name: kubernetes
    description: kubernets repo
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install kubelet, kubectl and kubernetes-cni
  yum:
    name:
      - kubelet-{{ k8s_version }}
      - kubectl-{{ k8s_version }}
      - kubeadm-{{ k8s_version }}
    state: installed

- name: Detect docker's cgroup-driver
  shell: docker info 2>/dev/null |grep -i cgroup | cut -d":" -f2 | tr -d " "
  register: docker_cgroup_driver
  
- replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '--cgroup-driver=(systemd|cgroupfs)'
    replace: '--cgroup-driver={{docker_cgroup_driver.stdout}}'
    backup: no

- name: Add netbridge config ip6
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.bridge.bridge-nf-call-ip6tables = 1'
    state: present
    create: yes

- name: Add netbridge config ip4
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    sysctl_set: yes
    reload: yes

- name: update sysctl
  command: sysctl --system

- name: Configure kubelet swap enabled
  lineinfile:
    path: /etc/sysconfig/kubelet
    regexp: "^KUBELET_EXTRA_ARGS="
    line: "KUBELET_EXTRA_ARGS=--fail-swap-on=false"

- name: Start kubelet
  systemd:
    state: started
    daemon_reload: yes
    name: kubelet
    enabled: yes
